[global]
error_log = /proc/self/fd/2

; https://github.com/docker-library/php/pull/725#issuecomment-443540114
log_limit = 8192

[www]
; if we send this to /proc/self/fd/1, it never appears
access.log = /proc/self/fd/2

clear_env = no

; Ensure worker stdout and stderr are sent to the main error log.
catch_workers_output = yes
decorate_workers_output = no
pm.status_path = /status

php_admin_value[error_reporting] = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED & ~E_WARNING
php_admin_flag[log_errors] = on
php_admin_flag[display_errors] = off

access.format='{"remote_addr":"%R","remote_user":"%u","time_local":"%{%Y-%m-%dT%H:%M:%S%z}T","request":"%m %r%Q%q","status":"%s", "script":"%f", "request_time":"%{mili}d", "memory":"%{kilo}M", "cpu":"%C"}'
